query Albums($title: String!, $name: String!) {
  albums(where: { name: $title, artists: { name: $name } }) {
    name
    jp_name
    image {
      url
    }
    artists {
      name
      jp_name
    }
    tracks {
      title
    }
  }
}
